name: test-oidc-integration

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  id-token: write # Strictly required for creating the OIDC token
  contents: read  # Required for checking out the repository

jobs:
  test-jfrog-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # Using the secret directly; ensure the secret itself doesn't have a trailing slash
          JF_URL: https://${{ secrets.JF_URL }}
          JF_PROJECT: ${{ secrets.JF_PROJECT }}
        with:
          oidc-provider-name: soumilv-oidc-integration

      - name: Test JFrog Connection
        run: |
          echo "Testing OIDC connection to JFrog for Pull Request..."
          jf rt ping
