name: "Frogbot Scan Pull Request"

# Trigger only when a pull request is created
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read
  id-token: write # Mandatory for OIDC

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - uses: actions/checkout@v4 # Updated to v4 for security/performance
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: soumilv-oidc-integration
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_URL: https://${{ secrets.JF_URL }}/
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_PROJECT: ${{ secrets.JF_PROJECT }}
          # Note: JF_ACCESS_TOKEN is omitted because we are testing OIDC
